sequenceDiagram
  participant User 
  participant Product Store 
  participant Cosmo FT

  User ->> Product Store: redeem-reward-tokens(amount uint)
  activate  Product Store
  Product Store ->> Cosmo FT: destroy-token(amount, owner)
  activate Cosmo FT
  alt is contract paused
  Cosmo FT ->> Product Store: returns the error
  else
   alt (tx-sender == owner) || (tx-sender == contract-owner)
   Cosmo FT ->> Product Store: returns the result
   else
   Cosmo FT ->> Product Store: returns the unauthorized caller error
   end
  end
  deactivate Cosmo FT
  Product Store ->> User: returns the result obtained from Cosmo FT
  deactivate Product Store